using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection;
using System.Text;
using BepInEx.Bootstrap;
using BepInEx.Logging;
using Comfort.Common;
using UnityEngine;
using BepInExPaths = BepInEx.Paths;
using CompressionLevel = System.IO.Compression.CompressionLevel;

namespace EasyMountingClient
{
    internal static class SupportPackage
    {
        public static void Generate()
        {
            try
            {
                string outDir = Path.Combine(BepInExPaths.GameRootPath, "EasyMounting-Support");
                Directory.CreateDirectory(outDir);
                string zipPath = Path.Combine(outDir, $"EasyMounting-Support-{DateTime.Now:yyyyMMdd-HHmmss}.zip");

                var notes = new List<string>();
                using (var fileStream = new FileStream(zipPath, FileMode.Create, FileAccess.Write))
                using (var zip = new ZipArchive(fileStream, ZipArchiveMode.Create))
                {
                    FlushBepInExDiskLog(notes);
                    TryAddFile(zip, Path.Combine(BepInExPaths.BepInExRootPath, "LogOutput.log"), "LogOutput.log", notes);
                    TryAddFile(zip, Path.Combine(BepInExPaths.ConfigPath, Plugin.PluginGuid + ".cfg"), Plugin.PluginGuid + ".cfg", notes);
                    TryAddFile(zip,
                        Path.Combine(BepInExPaths.GameRootPath, "SPT", "user", "mods", "EasyMounting", "Config", "config.json"),
                        "server-config.json", notes);

                    AddNewestServerLogs(zip, notes);
                    AddTextEntry(zip, "summary.txt", BuildSummary(notes));
                    AddTextEntry(zip, "readme.txt", BuildReadme());
                }
                SetZipComment(zipPath, BuildReadme());

                Plugin.Log.LogInfo(
                    "Support package created: " + zipPath + " - to share it, upload the zip to a temporary " +
                    "file-sharing service such as https://wormhole.app/ and post the resulting link.");

                if (Plugin.CleanupOldPackages.Value)
                {
                    CleanupOldPackages(outDir, zipPath, notes);
                }

                try
                {
                    Process.Start("explorer.exe", "/select,\"" + zipPath + "\"");
                }
                catch (Exception ex)
                {
                    Plugin.Log.LogWarning("Could not open Explorer for the support package: " + ex.Message);
                }
            }
            catch (Exception ex)
            {
                Plugin.Log.LogError("Support package generation failed: " + ex);
            }
        }

        private static string BuildReadme()
        {
            return
                "This support package was generated by the EasyMounting mod (hotkey in the F12 config manager,\r\n" +
                "section 'Support'). It contains the BepInEx log, EasyMounting configuration and a summary of\r\n" +
                "loaded plugins and active mounting settings.\r\n" +
                "\r\n" +
                "To share it: upload the zip to a temporary file-sharing service such as https://wormhole.app/\r\n" +
                "and post the resulting link (a fresh link per report keeps old packages from piling up anywhere\r\n" +
                "public).\r\n" +
                "\r\n" +
                "NOTE: server-config.json and the spt-server-* logs come from the LOCAL SPT install next to\r\n" +
                "this game client. If you play on a remote server (e.g. Fika), they may not describe the\r\n" +
                "server you actually play on.\r\n" +
                "\r\n" +
                "PRIVACY NOTE: game and server logs can contain your in-game profile name and the list of\r\n" +
                "installed mods. Review the files before posting the zip publicly.\r\n";
        }
        private static void CleanupOldPackages(string outDir, string currentZipPath, List<string> notes)
        {
            try
            {
                foreach (var file in Directory.GetFiles(outDir, "EasyMounting-Support-*.zip"))
                {
                    if (string.Equals(file, currentZipPath, StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }
                    File.Delete(file);
                    notes.Add("deleted old package: " + file);
                }
            }
            catch (Exception ex)
            {
                Plugin.Log.LogWarning("Could not clean up old support packages: " + ex.Message);
            }
        }
        private static void SetZipComment(string zipPath, string comment)
        {
            try
            {
                byte[] commentBytes = Encoding.UTF8.GetBytes(comment);
                if (commentBytes.Length > ushort.MaxValue)
                {
                    Array.Resize(ref commentBytes, ushort.MaxValue);
                }

                using (var stream = new FileStream(zipPath, FileMode.Open, FileAccess.ReadWrite))
                {
                    if (stream.Length < 22)
                    {
                        return;
                    }

                    stream.Seek(-22, SeekOrigin.End);
                    var eocd = new byte[4];
                    stream.Read(eocd, 0, 4);
                    bool isEocdSignature = eocd[0] == 0x50 && eocd[1] == 0x4B && eocd[2] == 0x05 && eocd[3] == 0x06;
                    if (!isEocdSignature)
                    {
                        Plugin.Log.LogWarning("Zip end-of-central-directory record not found where expected - skipping archive comment.");
                        return;
                    }

                    stream.Seek(-2, SeekOrigin.End);
                    stream.WriteByte((byte)(commentBytes.Length & 0xFF));
                    stream.WriteByte((byte)((commentBytes.Length >> 8) & 0xFF));
                    stream.Seek(0, SeekOrigin.End);
                    stream.Write(commentBytes, 0, commentBytes.Length);
                }
            }
            catch (Exception ex)
            {
                Plugin.Log.LogWarning("Could not set zip archive comment: " + ex.Message);
            }
        }

        private static void AddNewestServerLogs(ZipArchive zip, List<string> notes)
        {
            try
            {
                string logsDir = Path.Combine(BepInExPaths.GameRootPath, "SPT", "user", "logs");
                if (!Directory.Exists(logsDir))
                {
                    notes.Add("missing: " + logsDir + " (no local SPT server, e.g. Fika client)");
                    return;
                }
                var newest = new DirectoryInfo(logsDir)
                    .GetFiles("*.log*", SearchOption.AllDirectories)
                    .OrderByDescending(f => f.LastWriteTimeUtc)
                    .Take(2)
                    .ToList();
                if (newest.Count == 0)
                {
                    notes.Add("missing: no log files under " + logsDir);
                    return;
                }

                foreach (var file in newest)
                {
                    string relative = file.FullName.Substring(logsDir.Length).TrimStart(Path.DirectorySeparatorChar);
                    TryAddFile(zip, file.FullName, "spt-server-" + relative.Replace(Path.DirectorySeparatorChar, '_'), notes);
                }
            }
            catch (Exception ex)
            {
                notes.Add("failed: SPT server log lookup - " + ex.Message);
            }
        }

        private static void FlushBepInExDiskLog(List<string> notes)
        {
            try
            {
                foreach (var listener in BepInEx.Logging.Logger.Listeners)
                {
                    if (listener is DiskLogListener diskListener)
                    {
                        diskListener.LogWriter?.Flush();
                    }
                }
            }
            catch (Exception ex)
            {
                notes.Add("note: could not flush the BepInEx log before copying - the newest ~2s of lines may be missing (" + ex.Message + ")");
            }
        }

        private static void TryAddFile(ZipArchive zip, string sourcePath, string entryName, List<string> notes)
        {
            try
            {
                if (!File.Exists(sourcePath))
                {
                    notes.Add("missing: " + sourcePath);
                    return;
                }

                var entry = zip.CreateEntry(entryName, CompressionLevel.Fastest);
                using (var source = new FileStream(sourcePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                using (var target = entry.Open())
                {
                    source.CopyTo(target);
                    notes.Add($"included: {entryName} ({source.Length} bytes) from {sourcePath}");
                }
            }
            catch (Exception ex)
            {
                notes.Add("failed: " + sourcePath + " - " + ex.Message);
            }
        }

        private static void AddTextEntry(ZipArchive zip, string entryName, string content)
        {
            var entry = zip.CreateEntry(entryName, CompressionLevel.Fastest);
            using (var writer = new StreamWriter(entry.Open(), Encoding.UTF8))
            {
                writer.Write(content);
            }
        }

        private static string BuildSummary(List<string> notes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("EasyMounting support summary");
            sb.AppendLine("Generated: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss zzz"));
            sb.AppendLine($"Plugin: {Plugin.PluginName} v{Plugin.PluginVersion} (GUID {Plugin.PluginGuid})");
            sb.AppendLine($"Game version: {Application.version} (Unity {Application.unityVersion})");
            sb.AppendLine();

            if (!Plugin.DebugMountLogging.Value)
            {
                sb.AppendLine("NOTE: DebugMountLogging was OFF while this package was generated - LogOutput.log");
                sb.AppendLine("contains no [MountDebug] mount traces. Enable it (F12 -> Debug) and reproduce the");
                sb.AppendLine("issue before generating another package if mount traces are needed.");
                sb.AppendLine();
            }

            sb.AppendLine("== EasyMounting client config ==");
            try
            {
                var config = Plugin.BoundConfig;
                if (config == null)
                {
                    sb.AppendLine("(config not captured)");
                }
                else
                {
                    foreach (var definition in config.Keys.OrderBy(d => d.Section + "." + d.Key, StringComparer.Ordinal))
                    {
                        sb.AppendLine($"{definition.Section}.{definition.Key} = {config[definition].BoxedValue}");
                    }
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine("(failed to read: " + ex.Message + ")");
            }
            sb.AppendLine();

            sb.AppendLine("== Server-provided MountingSettings (as received by this client) ==");
            try
            {
                if (!Singleton<BackendConfigSettingsClass>.Instantiated)
                {
                    sb.AppendLine("(not available yet - generate the package after logging in or while in a raid)");
                }
                else
                {
                    var mountingSettings = Singleton<BackendConfigSettingsClass>.Instance.MountingSettings;
                    DumpProperties(sb, "MovementSettings", mountingSettings.MovementSettings);
                    DumpProperties(sb, "PointDetectionSettings", mountingSettings.PointDetectionSettings);
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine("(failed to read: " + ex.Message + ")");
            }
            sb.AppendLine();

            sb.AppendLine("== Loaded BepInEx plugins ==");
            try
            {
                foreach (var pluginInfo in Chainloader.PluginInfos.OrderBy(p => p.Key, StringComparer.Ordinal))
                {
                    sb.AppendLine($"{pluginInfo.Key} = {pluginInfo.Value.Metadata.Version}");
                }
            }
            catch (Exception ex)
            {
                sb.AppendLine("(failed to read: " + ex.Message + ")");
            }
            sb.AppendLine();

            sb.AppendLine("== Collected files ==");
            foreach (var note in notes)
            {
                sb.AppendLine(note);
            }

            return sb.ToString();
        }

        private static void DumpProperties(StringBuilder sb, string title, object settings)
        {
            sb.AppendLine("-- " + title + " --");
            if (settings == null)
            {
                sb.AppendLine("(null)");
                return;
            }
            foreach (var property in settings.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                object value;
                try
                {
                    value = property.GetValue(settings);
                }
                catch
                {
                    continue;
                }
                sb.AppendLine($"{property.Name} = {value}");
            }
        }
    }
}
